### ISSUE TITLE
Script 'Main SQL' failed: Could not find the SQL file.

### ISSUE THREAD

**Issue by mattwire** [systopia/de.systopia.sqltasks#2] opened 2017-10-20 20:08 UTC
On new install on 4.7.25 on top of drupal/joomla I create my first task (eg. select * from civicrm_navigation) and try to run it.

I get the following error:
"Script 'Main SQL' failed: Could not find the SQL file."

Will try to debug if I get chance @systopia have you seen this before?

**Comment by systopia** [comment] 2017-10-27 19:19
That's weird, it's exactly the kind of code that worked for CiviSEPA (https://github.com/Project60/org.project60.sepa/pull/438). 

@mattwire Have you already found a solution?

**Comment by pbatroff** [comment] 2017-11-02 10:59
Ran into the same Problem. Source of it is this [issue](https://issues.civicrm.org/jira/browse/CRM-20428). The API function `CRM_Utils_File::sourceSQLFile` got changed.

Proposed solution: Make a version check for < 4.7.20 and use old code, new code should directly call `CRM_Utils_File::runSqlQuery`.

Needs testing, I just checked the versions and CiviCode.

**Comment by mattwire** [comment] 2017-11-02 12:11
@pbatroff Great! I have not had time to look at the issue yet.  If you create a patch I will be happy to test, otherwise I will try to create a patch when I have some time.

**Comment by systopia** [comment] 2017-11-02 12:59
> Proposed solution: Make a version check for < 4.7.20 and use old code, new code should directly call CRM_Utils_File::runSqlQuery.

The problem was indeed that @JohnFF has not only split the ``CRM_Utils_File::sourceSQLFile`` method, but also changed its signature.

I created a fix with a version switch in the ``dev_2`` branch. 

@mattwire: Could you check if it works for you?

**Comment by JohnFF** [comment] 2017-11-02 15:30
@systopia The problem was that the file was never found to begin with. Previously it just it failed silently, and it informing the user of the error is a significant improvement. I'm aware of other extensions that have benefited as well.

**Comment by systopia** [comment] 2017-11-02 15:34
> @systopia The problem was that the file was never found to begin with. Previously it just it failed silently, and it informing the user of the error is a significant improvement. I'm aware of other extensions that have benefited as well.

@JohnFF: That might be, but we were using the function by passing the script content directly - and that *definitely* worked. And since ``4.7.20`` it apparently doesn't.

**Comment by JohnFF** [comment] 2017-11-02 15:42
The crazily overloaded function  needed splitting - doing it fixed bugs all over the place. If it ever hadn't have worked you'd have no way of knowing! New version is much better. Having checked the function headers those parameters won't make a difference in your case, afaict.

I'd recommend using the function as it was intentionally designed - with a source SQL file, rather than adding version checks.

**Comment by systopia** [comment] 2017-11-02 15:51
> I'd recommend using the function as it was intentionally designed - with a source SQL file, rather than adding version checks.

Well, it was intended to be used both ways, otherwise the ``$isQueryString`` parameter would be pretty weird... :-)

In our scenario we don't have a file - just the SQL string. But it should work just fine with the version check, thanks.

**Comment by mattwire** [comment] 2017-11-02 16:33
@systopia @pbatroff Just tested this now, pleased to say it's working well now with branch dev_2 (Joomla, CiviCRM 4.7.25)

**Comment by pbatroff** [comment] 2017-11-03 10:40
Works on our system as well with civi 4.7.24

**Comment by systopia** [comment] 2017-11-03 12:12
released with ``0.4.alpha1``

**Comment by systopia** [comment] 2017-11-03 12:12
Thanks for the feedback, guys.

**Closed by systopia** 2017-11-03 12:12 UTC
Labels: bug
